### ISSUE TITLE
Time comparison between Serial Mode and Parallel Mode

### ISSUE THREAD

**Issue by zhaolun7** [CNS-OIST/STEPS#34]
is there any comparison about running time between Serial Mode and Parallel Mode on a complex mesh sample? 

I notice that opt_method=2 is not allowed to add in Parallel Mode, so what is the default ordering behavior in Parallel Mode?
With specificying opt_method=2 in Serial Mode, do the times differ significantly in magnitude between these two modes?

another question about example: https://steps.sourceforge.net/manual/API_2/STEPS_Tutorial_Distributed.html
I replace the msh file and remove code about two divided physics group, it will cost about 100 seconds for every step time (DT = 2.0e-5) and about 15 hours to finish for total 10ms. 
![image](https://github.com/CNS-OIST/STEPS/assets/16096787/1a44152f-4989-4f3e-8455-b1651c847eba)

In the final code of python, it just run to differrent timestamp, how to know which part cost the most time?

**Comment by iahepburn** [comment]
Hello, 
In general, the serial solver is not able to cope very well with complex meshes and so we strongly recommend using the parallel solvers. In the original 'EField' paper we have some comparisons between the different optimisations (se e.g. https://www.frontiersin.org/files/Articles/56463/fncom-07-00129-r2/image_m/fncom-07-00129-g008.jpg), but that work is now quite dated and we strongly recommend using a parallel solver for any complex mesh, and with a large number of cores if possible. 

In a 2016 paper we have some performance comparisons between serial and parallel, showing up to a 3600x speedup in parallel, e.g. https://www.frontiersin.org/files/Articles/235291/fninf-11-00013-HTML/image_m/fninf-11-00013-g011.jpg

So, with regards to your second query, in a parallel simulation performance depends largely on the number of cores used. If this is run on a desktop (with a small number of cores) and the mesh is quite large then the performance can be quite slow and similar to serial performance. However, it is expected to scale meaning performance can be vastly improved by running on a computer cluster. In our recent paper on this solver we show some performances with different size meshes so it will give you an idea of performance of your mesh. This shows performance of the calcium burst model in a mesh of order ~1M tetrahedrons: 
(https://www.frontiersin.org/files/Articles/883742/fninf-16-883742-HTML/image_m/fninf-16-883742-g010.jpg)

Do you have access to a computer cluster in which you are able to run your simulations? If so, I would suggest that as the next step because that should significantly improve performance of this model.
